name: Pull request validation

on:
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  call-workflow:
    strategy:
      matrix:
        node-version: [20.x]
        switch: [current]
    uses: compulim/workflows/.github/workflows/pull-request-validation.yml@main
    with:
      node-version: ${{ matrix.node-version }}
      package-name: iter-fest
      skip-integration-test: false
      switch: ${{ matrix.switch }}
